name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master
pr:
- master
jobs:
- job: Test_Build_Deploy
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - task: Powershell@2
      displayName: 'Test'
      env:
        BUILD_NAME: $(Build.BuildNumber)
        TEST2: $(random.name)
        TEST3: $(test3)
        GITHUB_PAT: $(github.pat)
      inputs:
        targetType: 'filePath'
        filePath: .\Test.ps1
        errorActionPreference: 'stop'
        failOnStderr: true

    - powershell: . ./test.ps1
      displayName: 'Shortcut Syntax test on pwsh6'
      pwsh: true